---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  requirements_path: requirements.yml
  ansible_verbose: false
  ansible_verbosity: 2
  ignore_paths_from_root:
    - .kitchen

platforms:
  - name: ubuntu-14.04
    driver:
      box: bento/ubuntu-14.04
  - name: centos-7.2
    driver:
      box: bento/centos-7.2

suites:
  - name: default
    driver:
      network:
        - ["private_network", { ip: "172.29.129.35" }]

transport:
  max_ssh_sessions: 4
